# Site settings
name: fuzeyi
email: 706596204@qq.com
author: Fu Zeyi
url: https://fuzeyi.github.io/
resume_site: https://fuzeyi.github.io/
github: https://github.com/fuzeyi/
baseurl: ""
description: 不流俗，不盲从，不负此生!
meta_description: 付泽义;个人博客;不流俗，不盲从，不负此生！
motto: Not the remorse, not blindly follow, not in this lifetime.
banner: 不流俗，不盲从，不负此生。
encoding: utf-8
highlighter: rouge

permalink: /:categories/:year/:month/:day/:title/
#permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: fuzeyi

# Build settings
markdown: kramdown

FB:
  comments :
    #provider : duoshuo
    #duoshuo:
      #   short_name : luoyan35714
     #disqus :
        # short_name : freudkang
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light